# Generated by Django 5.1.7 on 2025-04-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='saved_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
